export const GET_IMAGES_INFO        = 'GET_IMAGES_INFO';
export const DELETE_PROFILE_IMAGE   = 'DELETE_IMAGE';
export const GET_PROFILE_IMAGE      = 'GET_PROFILE_IMAGE';
export const UPDATE_CATEGORY_NAME   = 'UPDATE_CATEGORY_NAME';
export const ALL_CATEGORIES       = 'COUNT_CATEGORIES';